#include "gti/cpp_backend.h"

#include <string_view>

int main() {
  const lang::Program program;
  const lang::SemanticModel semantics;
  const lang::HirProgram hir;
  const lang::MirProgram mir;
  const lang::OptimizationResult optimizations;

  const lang::BackendArtifact artifact =
      lang::CppBackend().generate({.program = program,
                                   .semantics = semantics,
                                   .hir = hir,
                                   .mir = mir,
                                   .optimizations = optimizations});
  return artifact.kind == lang::BackendArtifactKind::Source &&
                 artifact.extension == ".cpp" &&
                 artifact.contents.find("// Generated by GTI.") !=
                     std::string_view::npos
             ? 0
             : 1;
}
