#include "gti/cpp_backend.h"
#include "gti/frontend.h"
#include "gti/optimizer.h"

#include <string_view>

int main() {
  const lang::FrontendResult frontend =
      lang::Frontend().analyze("backend-smoke.gti", R"(
int32_t leaf() { return (7); }
int32_t relay() { return leaf(); }
int32_t choose(bool first, int32_t left, int32_t right) {
  if (first) { return left; }
  return right;
}
mut int32_t cleanup_trace = 0;
class Cleanup {
public:
  ~Cleanup() { cleanup_trace = 1; }
};
int32_t cleanup_leaf() {
  Cleanup value{};
  return cleanup_trace;
}
int main() { return choose(true, relay(), 9) - 7 + cleanup_leaf(); }
)");
  if (!frontend.canGenerateCode()) {
    return 1;
  }
  const lang::OptimizationResult optimizations =
      lang::OptimizationPipeline().run(frontend.hir,
                                       lang::OptimizationLevel::O0);

  const lang::BackendArtifact artifact =
      lang::CppBackend().generate({.program = frontend.program,
                                   .semantics = frontend.semantics,
                                   .hir = frontend.hir,
                                   .mir = frontend.mir,
                                   .sourceMir = &frontend.mir,
                                   .optimizations = optimizations});
  return artifact.kind == lang::BackendArtifactKind::Source &&
                 artifact.extension == ".cpp" &&
                 artifact.contents.find("// Generated by GTI.") !=
                     std::string_view::npos &&
                 artifact.contents.find(
                     "// GTI verified-MIR body: scalar-cfg-v1") !=
                     std::string_view::npos &&
                 artifact.contents.find(
                     "// GTI verified-MIR body: scalar-cfg-v1") !=
                     std::string_view::npos &&
                 artifact.contents.find(
                     "// GTI verified-MIR body: scalar-cfg-v1") !=
                     std::string_view::npos &&
                 artifact.contents.find(".construct()") !=
                     std::string_view::npos &&
                 artifact.contents.find(".destroy()") !=
                     std::string_view::npos &&
                 artifact.contents.find(
                     "// GTI verified-MIR body: scalar-cfg-v1 "
                     "destructor-instance") != std::string_view::npos
             ? 0
             : 1;
}
