#include "gti/native_header.h"

#include <algorithm>
#include <cstdint>
#include <iomanip>
#include <sstream>
#include <stdexcept>
#include <string>
#include <unordered_map>
#include <unordered_set>
#include <utility>
#include <vector>

namespace lang {
namespace {

struct NativeRecord {
  const ClassDecl *declaration = nullptr;
  const ClassTypeInfo *info = nullptr;
  std::string cName;
};

using NativeOpaqueHandle = NativeRecord;

struct NativeFunction {
  const FunctionDecl *declaration = nullptr;
  const FunctionInfo *info = nullptr;
};

std::string emittedScope(std::string_view scope, std::size_t index) {
  return index == 0 && scope == "std" ? "__gti_std" : std::string(scope);
}

std::string qualifiedCppName(const ClassTypeInfo &info) {
  std::string result = "::";
  for (std::size_t index = 0; index < info.namespaceScope.size(); ++index) {
    result += emittedScope(info.namespaceScope[index], index);
    result += "::";
  }
  result += info.declaration->name().lexeme;
  return result;
}

std::string encodedCRecordName(const ClassTypeInfo &info) {
  std::ostringstream output;
  output << "gti_cabi_";
  for (const unsigned char byte : info.qualifiedName) {
    output << std::hex << std::setw(2) << std::setfill('0')
           << static_cast<unsigned int>(byte);
  }
  return output.str();
}

void openCppNamespaces(std::ostream &output,
                       const std::vector<std::string> &scopes) {
  for (std::size_t index = 0; index < scopes.size(); ++index) {
    output << "namespace " << emittedScope(scopes[index], index) << " {\n";
  }
}

void closeCppNamespaces(std::ostream &output,
                        const std::vector<std::string> &scopes) {
  for (auto scope = scopes.rbegin(); scope != scopes.rend(); ++scope) {
    output << "} // namespace "
           << emittedScope(*scope, static_cast<std::size_t>(
                                       std::distance(scope, scopes.rend()) - 1))
           << "\n";
  }
}

class NativeHeaderEmitter {
public:
  NativeHeaderEmitter(const Program &program, const SemanticModel &semantics,
                      TargetInfo target)
      : program(program), semantics(semantics), target(std::move(target)) {}

  std::string emit() {
    collect(program.declarations());
    assignCNames();
    orderRecords();

    std::ostringstream body;
    body << "/* Generated by GTI. Do not edit.\n"
            " * This header is a C ABI boundary and is valid in both C17 and "
            "C++20/C++23.\n"
            " * Opaque handles are incomplete nominal types and may cross "
            "only by pointer.\n"
            " * C++ implementations may wrap arbitrary C++ internals, but "
            "must not let exceptions cross these functions.\n"
            " */\n\n"
            "#include <stddef.h>\n"
            "#include <stdint.h>\n"
            "#include <gti/c_abi.h>\n"
            "#ifdef __cplusplus\n"
            "#include <cstddef>\n"
            "#include <cstdint>\n"
            "#include <type_traits>\n"
            "#endif\n\n";

    emitCppBranch(body);
    body << "#else\n\n";
    emitCBranch(body);
    body << "#endif\n";

    const std::string contents = body.str();
    const std::string guard = headerGuard(contents);
    return "#ifndef " + guard + "\n#define " + guard + "\n\n" + contents +
           "\n#endif /* " + guard + " */\n";
  }

private:
  void collect(const StmtList &declarations) {
    for (const StmtPtr &statement : declarations) {
      if (const auto *conditional =
              dynamic_cast<const ConditionalStmt *>(statement.get())) {
        if (const StmtList *branch = conditional->activeBranch(target)) {
          collect(*branch);
        }
        continue;
      }
      if (const auto *namespaceDeclaration =
              dynamic_cast<const NamespaceDecl *>(statement.get())) {
        collect(namespaceDeclaration->declarations());
        continue;
      }
      if (const auto *classDeclaration =
              dynamic_cast<const ClassDecl *>(statement.get())) {
        const ClassTypeInfo *info = semantics.findClassType(*classDeclaration);
        if (info != nullptr && info->cAbiRecord && info->cAbiLayout &&
            !info->compilerPrivate) {
          const std::size_t index = records.size();
          records.push_back({.declaration = classDeclaration, .info = info});
          recordByClass.emplace(info->id, index);
        } else if (info != nullptr && info->cOpaqueHandle &&
                   !info->compilerPrivate) {
          const std::size_t index = opaqueHandles.size();
          opaqueHandles.push_back(
              {.declaration = classDeclaration, .info = info});
          opaqueByClass.emplace(info->id, index);
        }
        continue;
      }
      const auto *externC = dynamic_cast<const ExternCDecl *>(statement.get());
      if (externC == nullptr) {
        continue;
      }
      for (const StmtPtr &declaration : externC->declarations()) {
        const auto *function =
            dynamic_cast<const FunctionDecl *>(declaration.get());
        const FunctionInfo *info =
            function == nullptr ? nullptr : semantics.findFunction(*function);
        if (function != nullptr && info != nullptr &&
            info->linkage == LanguageLinkage::C && !info->compilerPrivate) {
          functions.push_back({.declaration = function, .info = info});
        }
      }
    }
  }

  void assignCNames() {
    std::unordered_set<std::string> used;
    const auto assignRoots = [&](auto &types) {
      for (NativeRecord &type : types) {
        if (type.info->namespaceScope.empty()) {
          type.cName = type.declaration->name().lexeme;
          used.insert(type.cName);
        }
      }
    };
    const auto assignNamespaced = [&](auto &types) {
      for (NativeRecord &type : types) {
        if (type.cName.empty()) {
          type.cName = encodedCRecordName(*type.info);
          while (!used.insert(type.cName).second) {
            type.cName += '_';
          }
        }
      }
    };
    assignRoots(records);
    assignRoots(opaqueHandles);
    assignNamespaced(records);
    assignNamespaced(opaqueHandles);
  }

  void orderRecord(ClassId id, std::unordered_set<ClassId> &visiting) {
    if (orderedRecordIds.contains(id)) {
      return;
    }
    const auto found = recordByClass.find(id);
    if (found == recordByClass.end() || !visiting.insert(id).second) {
      throw std::logic_error(
          "checked C ABI record graph is unavailable to native header");
    }
    const NativeRecord &record = records[found->second];
    for (const CAbiRecordFieldLayout &field : record.info->cAbiLayout->fields) {
      if (field.type.kind == SemanticType::Class) {
        orderRecord(field.type.classId, visiting);
      }
    }
    visiting.erase(id);
    orderedRecordIds.insert(id);
    orderedRecords.push_back(found->second);
  }

  void orderRecords() {
    std::unordered_set<ClassId> visiting;
    for (const NativeRecord &record : records) {
      orderRecord(record.info->id, visiting);
    }
  }

  const NativeRecord &nativeTypeFor(ClassId id) const {
    if (const auto found = recordByClass.find(id);
        found != recordByClass.end()) {
      return records[found->second];
    }
    if (const auto found = opaqueByClass.find(id);
        found != opaqueByClass.end()) {
      return opaqueHandles[found->second];
    }
    throw std::logic_error(
        "checked native C type is unavailable to native header");
  }

  std::string cppType(const SemanticType &type) const {
    switch (type.kind) {
    case SemanticType::Void:
      return "void";
    case SemanticType::Int8:
      return "std::int8_t";
    case SemanticType::Int16:
      return "std::int16_t";
    case SemanticType::Int32:
      return "std::int32_t";
    case SemanticType::Int64:
      return "std::int64_t";
    case SemanticType::UInt8:
      return "std::uint8_t";
    case SemanticType::UInt16:
      return "std::uint16_t";
    case SemanticType::UInt32:
      return "std::uint32_t";
    case SemanticType::UInt64:
      return "std::uint64_t";
    case SemanticType::Float:
      return "float";
    case SemanticType::Double:
      return "double";
    case SemanticType::StringView:
      return "::gti_c_string_view";
    case SemanticType::Class:
      return qualifiedCppName(*nativeTypeFor(type.classId).info);
    case SemanticType::RawPointer: {
      if (type.arguments.size() != 1) {
        break;
      }
      return std::string(type.pointerAccess == AccessMode::ReadOnly ? "const "
                                                                    : "") +
             cppType(type.arguments.front()) + "*";
    }
    default:
      break;
    }
    throw std::logic_error(
        "unsupported checked C ABI type reached native header backend");
  }

  std::string cType(const SemanticType &type) const {
    switch (type.kind) {
    case SemanticType::Void:
      return "void";
    case SemanticType::Int8:
      return "int8_t";
    case SemanticType::Int16:
      return "int16_t";
    case SemanticType::Int32:
      return "int32_t";
    case SemanticType::Int64:
      return "int64_t";
    case SemanticType::UInt8:
      return "uint8_t";
    case SemanticType::UInt16:
      return "uint16_t";
    case SemanticType::UInt32:
      return "uint32_t";
    case SemanticType::UInt64:
      return "uint64_t";
    case SemanticType::Float:
      return "float";
    case SemanticType::Double:
      return "double";
    case SemanticType::StringView:
      return "gti_c_string_view";
    case SemanticType::Class:
      return nativeTypeFor(type.classId).cName;
    case SemanticType::RawPointer: {
      if (type.arguments.size() != 1) {
        break;
      }
      return std::string(type.pointerAccess == AccessMode::ReadOnly ? "const "
                                                                    : "") +
             cType(type.arguments.front()) + "*";
    }
    default:
      break;
    }
    throw std::logic_error(
        "unsupported checked C ABI type reached native header backend");
  }

  void emitCppForward(std::ostream &output, const NativeRecord &record) const {
    openCppNamespaces(output, record.info->namespaceScope);
    output << "struct " << record.declaration->name().lexeme << ";\n";
    closeCppNamespaces(output, record.info->namespaceScope);
  }

  void emitCppRecord(std::ostream &output, const NativeRecord &record) const {
    openCppNamespaces(output, record.info->namespaceScope);
    output << "struct " << record.declaration->name().lexeme << " {\n";
    for (const CAbiRecordFieldLayout &field : record.info->cAbiLayout->fields) {
      output << "  " << cppType(field.type) << ' '
             << field.declaration->name().lexeme << ";\n";
    }
    output << "};\n";
    closeCppNamespaces(output, record.info->namespaceScope);
  }

  void emitCppAssertions(std::ostream &output,
                         const NativeRecord &record) const {
    const std::string type = qualifiedCppName(*record.info);
    const CAbiRecordLayout &layout = *record.info->cAbiLayout;
    output << "static_assert(std::is_standard_layout_v<" << type
           << "> && std::is_trivially_copyable_v<" << type
           << ">, \"GTI native record must remain a passive C ABI value\");\n"
           << "static_assert(sizeof(" << type << ") == " << layout.sizeBytes
           << ", \"GTI native record size mismatch\");\n"
           << "static_assert(alignof(" << type
           << ") == " << layout.abiAlignmentBytes
           << ", \"GTI native record alignment mismatch\");\n";
    for (const CAbiRecordFieldLayout &field : layout.fields) {
      output << "static_assert(offsetof(" << type << ", "
             << field.declaration->name().lexeme << ") == " << field.offsetBytes
             << ", \"GTI native record field offset "
             << "mismatch\");\n";
    }
  }

  template <typename TypeEmitter>
  void emitFunctionSignature(std::ostream &output,
                             const NativeFunction &function,
                             TypeEmitter emitType, bool cBranch) const {
    output << emitType(function.info->returnType) << ' '
           << function.info->externalSymbol << '(';
    if (function.info->parameterTypes.empty() && cBranch) {
      output << "void";
    }
    for (std::size_t index = 0; index < function.info->parameterTypes.size();
         ++index) {
      if (index != 0) {
        output << ", ";
      }
      output << emitType(function.info->parameterTypes[index]);
      if (index < function.declaration->parameters().size() &&
          !function.declaration->parameters()[index].name.lexeme.empty()) {
        output << ' ' << function.declaration->parameters()[index].name.lexeme;
      }
    }
    output << ");\n";
  }

  void emitCppFunction(std::ostream &output,
                       const NativeFunction &function) const {
    openCppNamespaces(output, function.info->namespaceScope);
    output << "extern \"C\" {\n";
    emitFunctionSignature(
        output, function,
        [this](const SemanticType &type) { return cppType(type); }, false);
    output << "}\n";
    closeCppNamespaces(output, function.info->namespaceScope);
  }

  void emitCppBranch(std::ostream &output) const {
    output << "#ifdef __cplusplus\n\n";
    for (const NativeRecord &record : records) {
      emitCppForward(output, record);
    }
    for (const NativeOpaqueHandle &handle : opaqueHandles) {
      emitCppForward(output, handle);
    }
    if (!records.empty() || !opaqueHandles.empty()) {
      output << '\n';
    }
    for (const std::size_t index : orderedRecords) {
      emitCppRecord(output, records[index]);
      output << '\n';
    }
    for (const NativeRecord &record : records) {
      emitCppAssertions(output, record);
    }
    if (!records.empty() && !functions.empty()) {
      output << '\n';
    }
    for (const NativeFunction &function : functions) {
      emitCppFunction(output, function);
    }
    output << '\n';
  }

  void emitCBranch(std::ostream &output) const {
    for (const NativeRecord &record : records) {
      output << "/* " << record.info->qualifiedName << " */\n"
             << "typedef struct " << record.cName << ' ' << record.cName
             << ";\n";
    }
    for (const NativeOpaqueHandle &handle : opaqueHandles) {
      output << "/* " << handle.info->qualifiedName << " (opaque handle) */\n"
             << "typedef struct " << handle.cName << ' ' << handle.cName
             << ";\n";
    }
    if (!records.empty() || !opaqueHandles.empty()) {
      output << '\n';
    }
    for (const std::size_t index : orderedRecords) {
      const NativeRecord &record = records[index];
      output << "struct " << record.cName << " {\n";
      for (const CAbiRecordFieldLayout &field :
           record.info->cAbiLayout->fields) {
        output << "  " << cType(field.type) << ' '
               << field.declaration->name().lexeme << ";\n";
      }
      output << "};\n\n";
    }
    for (const NativeRecord &record : records) {
      const CAbiRecordLayout &layout = *record.info->cAbiLayout;
      output << "_Static_assert(sizeof(" << record.cName
             << ") == " << layout.sizeBytes
             << ", \"GTI native record size mismatch\");\n"
             << "_Static_assert(_Alignof(" << record.cName
             << ") == " << layout.abiAlignmentBytes
             << ", \"GTI native record alignment mismatch\");\n";
      for (const CAbiRecordFieldLayout &field : layout.fields) {
        output << "_Static_assert(offsetof(" << record.cName << ", "
               << field.declaration->name().lexeme
               << ") == " << field.offsetBytes
               << ", \"GTI native record field offset mismatch\");\n";
      }
    }
    if (!records.empty() && !functions.empty()) {
      output << '\n';
    }
    for (const NativeFunction &function : functions) {
      emitFunctionSignature(
          output, function,
          [this](const SemanticType &type) { return cType(type); }, true);
    }
  }

  static std::string headerGuard(std::string_view contents) {
    std::uint64_t hash = 1469598103934665603ULL;
    for (const unsigned char byte : contents) {
      hash ^= byte;
      hash *= 1099511628211ULL;
    }
    std::ostringstream output;
    output << "GTI_NATIVE_BRIDGE_" << std::uppercase << std::hex
           << std::setw(16) << std::setfill('0') << hash << "_H";
    return output.str();
  }

  const Program &program;
  const SemanticModel &semantics;
  TargetInfo target;
  std::vector<NativeRecord> records;
  std::unordered_map<ClassId, std::size_t> recordByClass;
  std::vector<NativeOpaqueHandle> opaqueHandles;
  std::unordered_map<ClassId, std::size_t> opaqueByClass;
  std::vector<std::size_t> orderedRecords;
  std::unordered_set<ClassId> orderedRecordIds;
  std::vector<NativeFunction> functions;
};

} // namespace

BackendArtifact NativeHeaderBackend::generate(const BackendInput &input) {
  return {.kind = BackendArtifactKind::Source,
          .contents =
              NativeHeaderEmitter(input.program, input.semantics, input.target)
                  .emit(),
          .extension = ".h"};
}

} // namespace lang
