#include "gti/token.h"

namespace lang {

const std::unordered_map<std::string_view, TokenKind> keywords{
    {"and", TokenKind::AND},
    {"alignof", TokenKind::ALIGNOF},
    {"break", TokenKind::BREAK},
    {"case", TokenKind::CASE},
    {"class", TokenKind::CLASS},
    {"concept", TokenKind::CONCEPT},
    {"const", TokenKind::CONST},
    {"constexpr", TokenKind::CONSTEXPR},
    {"continue", TokenKind::CONTINUE},
    {"default", TokenKind::DEFAULT},
    {"delete", TokenKind::DELETE},
    {"do", TokenKind::DO},
    {"else", TokenKind::ELSE},
    {"enum", TokenKind::ENUM},
    {"extern", TokenKind::EXTERN},
    {"false", TokenKind::FALSE},
    {"for", TokenKind::FOR},
    {"if", TokenKind::IF},
    {"interface", TokenKind::INTERFACE},
    {"mut", TokenKind::MUT},
    {"namespace", TokenKind::NAMESPACE},
    {"operator", TokenKind::OPERATOR},
    {"or", TokenKind::OR},
    {"override", TokenKind::OVERRIDE},
    {"private", TokenKind::PRIVATE},
    {"public", TokenKind::PUBLIC},
    {"requires", TokenKind::REQUIRES},
    {"return", TokenKind::RETURN},
    {"static", TokenKind::STATIC},
    {"struct", TokenKind::STRUCT},
    {"sizeof", TokenKind::SIZEOF},
    {"switch", TokenKind::SWITCH},
    {"true", TokenKind::TRUE},
    {"union", TokenKind::UNION},
    {"unsafe", TokenKind::UNSAFE},
    {"using", TokenKind::USING},
    {"virtual", TokenKind::VIRTUAL},
    {"while", TokenKind::WHILE},

    {"auto", TokenKind::AUTO},
    {"int", TokenKind::INT},
    {"int8_t", TokenKind::INT8},
    {"int16_t", TokenKind::INT16},
    {"int32_t", TokenKind::INT32},
    {"int64_t", TokenKind::INT64},
    {"int8", TokenKind::INT8},
    {"int16", TokenKind::INT16},
    {"int32", TokenKind::INT32},
    {"int64", TokenKind::INT64},
    {"float", TokenKind::FLOAT},
    {"double", TokenKind::DOUBLE},
    {"uint", TokenKind::UINT},
    {"uint8_t", TokenKind::UINT8},
    {"uint16_t", TokenKind::UINT16},
    {"uint32_t", TokenKind::UINT32},
    {"uint64_t", TokenKind::UINT64},
    {"uint8", TokenKind::UINT8},
    {"uint16", TokenKind::UINT16},
    {"uint32", TokenKind::UINT32},
    {"uint64", TokenKind::UINT64},
    {"bool", TokenKind::BOOL},
    {"char", TokenKind::CHAR},
    {"expected", TokenKind::EXPECTED},
    {"nullptr_t", TokenKind::NULLPTR_TYPE},
    {"void", TokenKind::VOID},

    {"this", TokenKind::THIS},
    {"nullptr", TokenKind::NULLPTR},
    {"unexpected", TokenKind::UNEXPECTED},
};

} // namespace lang
