#!/usr/bin/env python3
"""Generate the Unicode 15.1 report-safe interval table.

The input must be the exact Unicode Character Database file named below.  The
hash pin prevents a host Unicode database, a newer UCD release, or line-ending
normalization from silently changing GTI's defined-failure report format.
"""

from __future__ import annotations

import argparse
import hashlib
import pathlib
import re
import sys


SOURCE_URL = (
    "https://www.unicode.org/Public/15.1.0/ucd/extracted/"
    "DerivedGeneralCategory.txt"
)
SOURCE_SHA256 = "760720ac034f96b630a3055879a744e0907184e8aa811e89ba34583a7a487e85"
SOURCE_VERSION_LINE = b"# DerivedGeneralCategory-15.1.0.txt"
ENTRY = re.compile(
    r"^([0-9A-F]{4,6})(?:\.\.([0-9A-F]{4,6}))?\s*;\s*([A-Za-z]{2})\b"
)


def accepted_category(category: str) -> bool:
    return category == "Zs" or category[0] in "LMNPS"


def intervals(source: bytes) -> list[tuple[int, int]]:
    result: list[tuple[int, int]] = []
    text = source.decode("utf-8")
    for line in text.splitlines():
        match = ENTRY.match(line)
        if match is None or not accepted_category(match.group(3)):
            continue
        first = int(match.group(1), 16)
        last = int(match.group(2) or match.group(1), 16)
        result.append((first, last))

    result.sort()
    merged: list[tuple[int, int]] = []
    for first, last in result:
        if merged and first <= merged[-1][1] + 1:
            merged[-1] = (merged[-1][0], max(merged[-1][1], last))
        else:
            merged.append((first, last))
    return merged


def render(values: list[tuple[int, int]]) -> str:
    lines = [
        "// Generated by scripts/generate_failure_unicode_table.py; do not edit.",
        "// Unicode version: 15.1.0",
        f"// Source: {SOURCE_URL}",
        f"// Source SHA-256: {SOURCE_SHA256}",
        "// Included General_Category values: L*, M*, N*, P*, S*, and Zs.",
        "inline constexpr UnicodeInterval kFailureReportSafeUnicode15_1[] = {",
    ]
    lines.extend(
        f"    {{0x{first:06X}u, 0x{last:06X}u}}," for first, last in values
    )
    lines.extend(
        [
            "};",
            "",
        ]
    )
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("source", type=pathlib.Path)
    parser.add_argument("output", type=pathlib.Path)
    parser.add_argument(
        "--check",
        action="store_true",
        help="fail unless the checked-in output already matches",
    )
    args = parser.parse_args()

    source = args.source.read_bytes()
    digest = hashlib.sha256(source).hexdigest()
    if digest != SOURCE_SHA256:
        print(
            f"unexpected DerivedGeneralCategory.txt SHA-256: {digest}",
            file=sys.stderr,
        )
        return 1
    if not source.startswith(SOURCE_VERSION_LINE + b"\n"):
        print("input is not Unicode DerivedGeneralCategory 15.1", file=sys.stderr)
        return 1

    output = render(intervals(source))
    if args.check:
        if not args.output.is_file() or args.output.read_text() != output:
            print(f"{args.output} is stale", file=sys.stderr)
            return 1
        return 0

    args.output.write_text(output)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
