#pragma once

#include "gti/ast.h"

#include <iomanip>
#include <limits>
#include <sstream>
#include <string>
#include <string_view>
#include <unordered_set>
#include <variant>
#include <vector>

namespace lang {

enum class CppStandard {
  Cpp20,
  Cpp23,
};

class CppEmitter final : public ExprVisitor, public StmtVisitor {
public:
  explicit CppEmitter(CppStandard standard = CppStandard::Cpp23,
                      TargetInfo target = TargetInfo::host())
      : standard(standard), target(std::move(target)) {}

  std::string emit(const Program &program) {
    output.str("");
    output.clear();
    indentation = 0;
    forwardedAliases.clear();
    sourceNamespaces.clear();
    currentReturnType = nullptr;

    output << "// Generated by GTI.\n"
              "#include <cstdint>\n"
              "#include <string>\n";
    if (containsExpectedType(program.declarations())) {
      output << (standard == CppStandard::Cpp23
                     ? "#include <expected>\n"
                     : "#include <nonstd/expected.hpp>\n");
    }
    if (containsRuntimeBinding(program.declarations())) {
      output << "#include <gti/runtime.hpp>\n";
    }
    output << '\n';

    emitForwardDeclarations(program);
    for (const StmtPtr &declaration : program.declarations()) {
      declaration->accept(*this);
      output << '\n';
    }
    return output.str();
  }

  void visitBlockStmt(const BlockStmt &stmt) override {
    writeIndent();
    emitBlock(stmt);
  }

  void visitAccessSpecifierDecl(const AccessSpecifierDecl &stmt) override {
    if (indentation > 0) {
      --indentation;
    }
    writeIndent();
    output << stmt.keyword().lexeme << ":\n";
    ++indentation;
  }

  void visitClassDecl(const ClassDecl &stmt) override {
    writeIndent();
    output << (stmt.kind() == ClassKind::Class ? "class " : "struct ")
           << stmt.name().lexeme << " {\n";
    ++indentation;
    for (const StmtPtr &member : stmt.members()) {
      member->accept(*this);
    }
    --indentation;
    writeIndent();
    output << "};\n";
  }

  void visitConditionalStmt(const ConditionalStmt &stmt) override {
    if (const StmtList *branch = stmt.activeBranch(target)) {
      for (const StmtPtr &statement : *branch) {
        statement->accept(*this);
      }
    }
  }

  void visitEmptyStmt(const EmptyStmt &) override {
    writeIndent();
    output << ";\n";
  }

  void visitExpressionStmt(const ExpressionStmt &stmt) override {
    writeIndent();
    emitExpression(stmt.expression());
    output << ";\n";
  }

  void visitForStmt(const ForStmt &stmt) override {
    writeIndent();
    output << "for (";
    emitForInitializer(stmt.initializer());
    output << "; ";
    emitExpression(stmt.condition());
    output << "; ";
    emitExpression(stmt.increment());
    output << ")";
    emitControlledBody(stmt.body());
  }

  void visitFunctionDecl(const FunctionDecl &stmt) override {
    if (stmt.runtimeBinding()) {
      return;
    }
    writeIndent();
    emitFunctionSignature(stmt);
    if (stmt.body()) {
      const TypeRef *enclosingReturnType = currentReturnType;
      currentReturnType = &stmt.returnType();
      output << ' ';
      emitBlock(*stmt.body());
      currentReturnType = enclosingReturnType;
    } else {
      output << ";\n";
    }
  }

  void visitIfStmt(const IfStmt &stmt) override {
    writeIndent();
    output << "if (";
    emitExpression(stmt.condition());
    output << ")";
    emitControlledBody(stmt.thenBranch());

    if (stmt.elseBranch()) {
      writeIndent();
      output << "else";
      emitControlledBody(stmt.elseBranch());
    }
  }

  void visitNamespaceAliasDecl(const NamespaceAliasDecl &stmt) override {
    if (forwardedAliases.contains(&stmt)) {
      return;
    }
    writeIndent();
    output << "namespace " << stmt.name().lexeme << " = ";
    emitNamePath(stmt.target());
    output << ";\n";
  }

  void visitNamespaceDecl(const NamespaceDecl &stmt) override {
    writeIndent();
    output << "namespace " << emittedNamespaceName(stmt.name()) << " {\n";
    sourceNamespaces.emplace_back(stmt.name().lexeme);
    ++indentation;
    for (const StmtPtr &declaration : stmt.declarations()) {
      declaration->accept(*this);
      output << '\n';
    }
    --indentation;
    sourceNamespaces.pop_back();
    writeIndent();
    output << "}\n";
  }

  void visitReturnStmt(const ReturnStmt &stmt) override {
    writeIndent();
    output << "return";
    if (stmt.value()) {
      output << ' ';
      emitExpression(stmt.value());
    } else if (currentReturnType != nullptr &&
               isExpectedVoid(*currentReturnType)) {
      output << " {}";
    }
    output << ";\n";
  }

  void visitVariableDecl(const VariableDecl &stmt) override {
    writeIndent();
    emitVariable(stmt);
    output << ";\n";
  }

  void visitWhileStmt(const WhileStmt &stmt) override {
    writeIndent();
    output << "while (";
    emitExpression(stmt.condition());
    output << ")";
    emitControlledBody(stmt.body());
  }

  void visitAssignExpr(const Assign &expr) override {
    output << '(' << expr.name().lexeme << ' ' << expr.oper().lexeme << ' ';
    emitExpression(expr.value());
    output << ')';
  }

  void visitBinaryExpr(const Binary &expr) override {
    output << '(';
    emitExpression(expr.left());
    output << ' ' << operatorSpelling(expr.oper()) << ' ';
    emitExpression(expr.right());
    output << ')';
  }

  void visitCallExpr(const Call &expr) override {
    emitExpression(expr.callee());
    output << '(';
    for (std::size_t index = 0; index < expr.arguments().size(); ++index) {
      if (index > 0) {
        output << ", ";
      }
      emitExpression(expr.arguments().at(index));
    }
    output << ')';
  }

  void visitGetExpr(const Get &expr) override {
    output << '(';
    emitExpression(expr.object());
    output << ")." << expr.name().lexeme;
  }

  void visitGroupingExpr(const Grouping &expr) override {
    output << '(';
    emitExpression(expr.expression());
    output << ')';
  }

  void visitLiteralExpr(const LiteralExpr &expr) override {
    const Literal &literal = expr.value();
    if (std::holds_alternative<std::nullptr_t>(literal)) {
      output << "nullptr";
    } else if (const auto *value = std::get_if<std::uint64_t>(&literal)) {
      output << *value;
      if (*value >
          static_cast<std::uint64_t>(
              std::numeric_limits<std::int64_t>::max())) {
        output << "ULL";
      }
    } else if (const auto *value = std::get_if<double>(&literal)) {
      output << std::setprecision(std::numeric_limits<double>::max_digits10)
             << *value;
    } else if (const auto *value = std::get_if<std::string>(&literal)) {
      output << "std::string{" << quote(*value) << ", " << value->size()
             << '}';
    } else if (const auto *value = std::get_if<bool>(&literal)) {
      output << (*value ? "true" : "false");
    } else {
      output << "{}";
    }
  }

  void visitLogicalExpr(const Logical &expr) override {
    output << '(';
    emitExpression(expr.left());
    output << ' ' << operatorSpelling(expr.oper()) << ' ';
    emitExpression(expr.right());
    output << ')';
  }

  void visitPostfixExpr(const Postfix &expr) override {
    output << '(';
    emitExpression(expr.expression());
    output << expr.oper().lexeme << ')';
  }

  void visitQualifiedNameExpr(const QualifiedName &expr) override {
    emitNamePath(expr.name());
  }

  void visitSelfExpr(const Self &) override { output << "(*this)"; }

  void visitSetExpr(const Set &expr) override {
    output << "((";
    emitExpression(expr.object());
    output << ")." << expr.name().lexeme << ' ' << expr.oper().lexeme << ' ';
    emitExpression(expr.value());
    output << ')';
  }

  void visitUnaryExpr(const Unary &expr) override {
    if (expr.oper().kind == TokenKind::MINUS) {
      if (const auto *literal =
              dynamic_cast<const LiteralExpr *>(expr.right().get());
          literal != nullptr) {
        const auto *magnitude = std::get_if<std::uint64_t>(&literal->value());
        if (magnitude != nullptr &&
            *magnitude == (std::uint64_t{1} << 63U)) {
          output << "(-9223372036854775807LL - 1)";
          return;
        }
      }
    }
    output << '(' << operatorSpelling(expr.oper());
    emitExpression(expr.right());
    output << ')';
  }

  void visitUnexpectedExpr(const Unexpected &expr) override {
    output << (standard == CppStandard::Cpp23 ? "std::unexpected("
                                               : "nonstd::make_unexpected(");
    emitExpression(expr.error());
    output << ')';
  }

  void visitVariableExpr(const Variable &expr) override {
    output << expr.name().lexeme;
  }

private:
  void emitForwardDeclarations(const Program &program) {
    const bool emittedTypes =
        emitTypeForwardDeclarations(program.declarations());
    const bool emittedAliases = emitAliasDeclarations(program.declarations());
    const bool emittedFunctions =
        emitFunctionForwardDeclarations(program.declarations());
    if (emittedTypes || emittedAliases || emittedFunctions) {
      output << '\n';
    }
  }

  bool emitTypeForwardDeclarations(const StmtList &declarations) {
    bool emitted = false;
    for (const StmtPtr &declaration : declarations) {
      if (const auto *conditional =
              dynamic_cast<const ConditionalStmt *>(declaration.get())) {
        if (const StmtList *branch = conditional->activeBranch(target)) {
          emitted = emitTypeForwardDeclarations(*branch) || emitted;
        }
      } else if (const auto *classDecl =
              dynamic_cast<const ClassDecl *>(declaration.get())) {
        writeIndent();
        output << (classDecl->kind() == ClassKind::Class ? "class " : "struct ")
               << classDecl->name().lexeme << ";\n";
        emitted = true;
      }
    }
    for (const StmtPtr &declaration : declarations) {
      if (const auto *namespaceDecl =
              dynamic_cast<const NamespaceDecl *>(declaration.get())) {
        writeIndent();
        output << "namespace " << emittedNamespaceName(namespaceDecl->name())
               << " {\n";
        sourceNamespaces.emplace_back(namespaceDecl->name().lexeme);
        ++indentation;
        emitTypeForwardDeclarations(namespaceDecl->declarations());
        --indentation;
        sourceNamespaces.pop_back();
        writeIndent();
        output << "}\n";
        emitted = true;
      }
    }
    return emitted;
  }

  bool emitAliasDeclarations(const StmtList &declarations) {
    bool emitted = false;
    for (const StmtPtr &declaration : declarations) {
      if (const auto *conditional =
              dynamic_cast<const ConditionalStmt *>(declaration.get())) {
        if (const StmtList *branch = conditional->activeBranch(target)) {
          emitted = emitAliasDeclarations(*branch) || emitted;
        }
      } else if (const auto *alias =
              dynamic_cast<const NamespaceAliasDecl *>(declaration.get())) {
        writeIndent();
        output << "namespace " << alias->name().lexeme << " = ";
        emitNamePath(alias->target());
        output << ";\n";
        forwardedAliases.insert(alias);
        emitted = true;
      } else if (const auto *namespaceDecl =
                     dynamic_cast<const NamespaceDecl *>(declaration.get());
                 namespaceDecl != nullptr &&
                 containsNamespaceAlias(namespaceDecl->declarations())) {
        writeIndent();
        output << "namespace " << emittedNamespaceName(namespaceDecl->name())
               << " {\n";
        sourceNamespaces.emplace_back(namespaceDecl->name().lexeme);
        ++indentation;
        emitAliasDeclarations(namespaceDecl->declarations());
        --indentation;
        sourceNamespaces.pop_back();
        writeIndent();
        output << "}\n";
        emitted = true;
      }
    }
    return emitted;
  }

  bool emitFunctionForwardDeclarations(const StmtList &declarations) {
    bool emitted = false;
    for (const StmtPtr &declaration : declarations) {
      if (const auto *conditional =
              dynamic_cast<const ConditionalStmt *>(declaration.get())) {
        if (const StmtList *branch = conditional->activeBranch(target)) {
          emitted = emitFunctionForwardDeclarations(*branch) || emitted;
        }
      } else if (const auto *function =
              dynamic_cast<const FunctionDecl *>(declaration.get());
          function != nullptr && !function->runtimeBinding()) {
        writeIndent();
        emitFunctionSignature(*function);
        output << ";\n";
        emitted = true;
      }
    }
    for (const StmtPtr &declaration : declarations) {
      if (const auto *namespaceDecl =
              dynamic_cast<const NamespaceDecl *>(declaration.get());
          namespaceDecl != nullptr &&
          containsFunction(namespaceDecl->declarations())) {
        writeIndent();
        output << "namespace " << emittedNamespaceName(namespaceDecl->name())
               << " {\n";
        sourceNamespaces.emplace_back(namespaceDecl->name().lexeme);
        ++indentation;
        emitFunctionForwardDeclarations(namespaceDecl->declarations());
        --indentation;
        sourceNamespaces.pop_back();
        writeIndent();
        output << "}\n";
        emitted = true;
      }
    }
    return emitted;
  }

  [[nodiscard]] bool containsNamespaceAlias(const StmtList &declarations) {
    for (const StmtPtr &declaration : declarations) {
      if (const auto *conditional =
              dynamic_cast<const ConditionalStmt *>(declaration.get())) {
        if (const StmtList *branch = conditional->activeBranch(target);
            branch != nullptr && containsNamespaceAlias(*branch)) {
          return true;
        }
        continue;
      }
      if (dynamic_cast<const NamespaceAliasDecl *>(declaration.get()) !=
          nullptr) {
        return true;
      }
      if (const auto *namespaceDecl =
              dynamic_cast<const NamespaceDecl *>(declaration.get());
          namespaceDecl != nullptr &&
          containsNamespaceAlias(namespaceDecl->declarations())) {
        return true;
      }
    }
    return false;
  }

  [[nodiscard]] bool containsFunction(const StmtList &declarations) {
    for (const StmtPtr &declaration : declarations) {
      if (const auto *conditional =
              dynamic_cast<const ConditionalStmt *>(declaration.get())) {
        if (const StmtList *branch = conditional->activeBranch(target);
            branch != nullptr && containsFunction(*branch)) {
          return true;
        }
        continue;
      }
      if (const auto *function =
              dynamic_cast<const FunctionDecl *>(declaration.get());
          function != nullptr && !function->runtimeBinding()) {
        return true;
      }
      if (const auto *namespaceDecl =
              dynamic_cast<const NamespaceDecl *>(declaration.get());
          namespaceDecl != nullptr &&
          containsFunction(namespaceDecl->declarations())) {
        return true;
      }
    }
    return false;
  }

  [[nodiscard]] bool containsRuntimeBinding(const StmtList &declarations) {
    for (const StmtPtr &declaration : declarations) {
      if (const auto *conditional =
              dynamic_cast<const ConditionalStmt *>(declaration.get())) {
        if (const StmtList *branch = conditional->activeBranch(target);
            branch != nullptr && containsRuntimeBinding(*branch)) {
          return true;
        }
        continue;
      }
      if (const auto *function =
              dynamic_cast<const FunctionDecl *>(declaration.get());
          function != nullptr && function->runtimeBinding()) {
        return true;
      }
      if (const auto *namespaceDecl =
              dynamic_cast<const NamespaceDecl *>(declaration.get());
          namespaceDecl != nullptr &&
          containsRuntimeBinding(namespaceDecl->declarations())) {
        return true;
      }
    }
    return false;
  }

  [[nodiscard]] static bool containsExpected(const TypeRef &type) {
    if (type.name.last().kind == TokenKind::EXPECTED) {
      return true;
    }
    for (const TypeRef &argument : type.arguments) {
      if (containsExpected(argument)) {
        return true;
      }
    }
    return false;
  }

  [[nodiscard]] bool containsExpectedType(const StmtList &statements) {
    for (const StmtPtr &statement : statements) {
      if (const auto *conditional =
              dynamic_cast<const ConditionalStmt *>(statement.get())) {
        if (const StmtList *branch = conditional->activeBranch(target);
            branch != nullptr && containsExpectedType(*branch)) {
          return true;
        }
      } else if (const auto *function =
              dynamic_cast<const FunctionDecl *>(statement.get())) {
        if (containsExpected(function->returnType())) {
          return true;
        }
        for (const Parameter &parameter : function->parameters()) {
          if (containsExpected(parameter.type)) {
            return true;
          }
        }
        if (function->body() &&
            containsExpectedType(function->body()->statements())) {
          return true;
        }
      } else if (const auto *variable =
                     dynamic_cast<const VariableDecl *>(statement.get())) {
        if (containsExpected(variable->type())) {
          return true;
        }
      } else if (const auto *block =
                     dynamic_cast<const BlockStmt *>(statement.get())) {
        if (containsExpectedType(block->statements())) {
          return true;
        }
      } else if (const auto *classDecl =
                     dynamic_cast<const ClassDecl *>(statement.get())) {
        if (containsExpectedType(classDecl->members())) {
          return true;
        }
      } else if (const auto *namespaceDecl =
                     dynamic_cast<const NamespaceDecl *>(statement.get())) {
        if (containsExpectedType(namespaceDecl->declarations())) {
          return true;
        }
      } else if (const auto *forStmt =
                     dynamic_cast<const ForStmt *>(statement.get())) {
        if (statementContainsExpected(forStmt->initializer()) ||
            statementContainsExpected(forStmt->body())) {
          return true;
        }
      } else if (const auto *ifStmt =
                     dynamic_cast<const IfStmt *>(statement.get())) {
        if (statementContainsExpected(ifStmt->thenBranch()) ||
            statementContainsExpected(ifStmt->elseBranch())) {
          return true;
        }
      } else if (const auto *whileStmt =
                     dynamic_cast<const WhileStmt *>(statement.get())) {
        if (statementContainsExpected(whileStmt->body())) {
          return true;
        }
      }
    }
    return false;
  }

  [[nodiscard]] bool statementContainsExpected(const StmtPtr &statement) {
    if (!statement) {
      return false;
    }
    const Stmt *raw = statement.get();
    if (const auto *conditional =
            dynamic_cast<const ConditionalStmt *>(raw)) {
      const StmtList *branch = conditional->activeBranch(target);
      return branch != nullptr && containsExpectedType(*branch);
    }
    if (const auto *variable = dynamic_cast<const VariableDecl *>(raw)) {
      return containsExpected(variable->type());
    }
    if (const auto *block = dynamic_cast<const BlockStmt *>(raw)) {
      return containsExpectedType(block->statements());
    }
    if (const auto *forStmt = dynamic_cast<const ForStmt *>(raw)) {
      return statementContainsExpected(forStmt->initializer()) ||
             statementContainsExpected(forStmt->body());
    }
    if (const auto *ifStmt = dynamic_cast<const IfStmt *>(raw)) {
      return statementContainsExpected(ifStmt->thenBranch()) ||
             statementContainsExpected(ifStmt->elseBranch());
    }
    if (const auto *whileStmt = dynamic_cast<const WhileStmt *>(raw)) {
      return statementContainsExpected(whileStmt->body());
    }
    return false;
  }

  void emitFunctionSignature(const FunctionDecl &function) {
    const bool isMain = sourceNamespaces.empty() &&
                        function.name().lexeme == "main" &&
                        isInt32(function.returnType());
    if (isMain) {
      output << "int";
    } else {
      emitType(function.returnType());
    }
    output << ' ' << function.name().lexeme << '(';
    for (std::size_t index = 0; index < function.parameters().size(); ++index) {
      if (index > 0) {
        output << ", ";
      }
      const Parameter &parameter = function.parameters().at(index);
      if (parameter.mutability == Mutability::Immutable) {
        output << "const ";
      }
      emitType(parameter.type);
      const bool byReference =
          parameter.mutability == Mutability::Immutable &&
          parameter.type.name.last().kind == TokenKind::STRING_TYPE;
      if (byReference) {
        output << " &";
      }
      if (!parameter.name.lexeme.empty()) {
        output << (byReference ? "" : " ") << parameter.name.lexeme;
      }
    }
    output << ')';
  }

  void emitType(const TypeRef &type) {
    switch (type.name.last().kind) {
    case TokenKind::INT:
    case TokenKind::INT32:
      output << "std::int32_t";
      return;
    case TokenKind::INT8:
      output << "std::int8_t";
      return;
    case TokenKind::INT16:
      output << "std::int16_t";
      return;
    case TokenKind::INT64:
      output << "std::int64_t";
      return;
    case TokenKind::UINT:
    case TokenKind::UINT32:
      output << "std::uint32_t";
      return;
    case TokenKind::UINT8:
      output << "std::uint8_t";
      return;
    case TokenKind::UINT16:
      output << "std::uint16_t";
      return;
    case TokenKind::UINT64:
      output << "std::uint64_t";
      return;
    default:
      break;
    }
    if (type.name.last().kind == TokenKind::STRING_TYPE) {
      output << "std::string";
      return;
    }
    if (type.name.last().kind == TokenKind::EXPECTED) {
      output << (standard == CppStandard::Cpp23 ? "std::expected<"
                                                 : "nonstd::expected<");
      emitType(type.arguments[0]);
      output << ", ";
      emitType(type.arguments[1]);
      output << '>';
      return;
    }
    emitNamePath(type.name);
  }

  [[nodiscard]] static bool isInt32(const TypeRef &type) {
    return type.name.last().kind == TokenKind::INT ||
           type.name.last().kind == TokenKind::INT32;
  }

  [[nodiscard]] static bool isExpectedVoid(const TypeRef &type) {
    return type.name.last().kind == TokenKind::EXPECTED &&
           type.arguments.size() == 2 &&
           type.arguments[0].name.last().kind == TokenKind::VOID;
  }

  void emitNamePath(const NamePath &path) {
    for (std::size_t index = 0; index < path.segments.size(); ++index) {
      if (index > 0) {
        output << "::";
      }
      if (index == 0 && path.segments[index].lexeme == "std") {
        output << "gti_std";
      } else {
        output << path.segments[index].lexeme;
      }
    }
  }

  [[nodiscard]] std::string emittedNamespaceName(const Token &name) const {
    return sourceNamespaces.empty() && name.lexeme == "std" ? "gti_std"
                                                              : name.lexeme;
  }

  void emitVariable(const VariableDecl &variable) {
    if (!variable.isMutable()) {
      output << "const ";
    }
    emitType(variable.type());
    output << ' ' << variable.name().lexeme;
    if (variable.initializer()) {
      output << " = ";
      emitExpression(variable.initializer());
    }
  }

  void emitForInitializer(const StmtPtr &initializer) {
    if (const auto *variable =
            dynamic_cast<const VariableDecl *>(initializer.get())) {
      emitVariable(*variable);
    } else if (const auto *expression =
                   dynamic_cast<const ExpressionStmt *>(initializer.get())) {
      emitExpression(expression->expression());
    }
  }

  void emitControlledBody(const StmtPtr &body) {
    if (const auto *block = dynamic_cast<const BlockStmt *>(body.get())) {
      output << ' ';
      emitBlock(*block);
      return;
    }

    output << '\n';
    ++indentation;
    body->accept(*this);
    --indentation;
  }

  void emitBlock(const BlockStmt &block) {
    output << "{\n";
    ++indentation;
    for (const StmtPtr &statement : block.statements()) {
      statement->accept(*this);
    }
    --indentation;
    writeIndent();
    output << "}\n";
  }

  void emitExpression(const ExprPtr &expression) {
    if (expression) {
      expression->accept(*this);
    }
  }

  void writeIndent() {
    for (std::size_t index = 0; index < indentation; ++index) {
      output << "  ";
    }
  }

  [[nodiscard]] static std::string_view operatorSpelling(const Token &oper) {
    if (oper.kind == TokenKind::AND) {
      return "&&";
    }
    if (oper.kind == TokenKind::OR) {
      return "||";
    }
    return oper.lexeme;
  }

  [[nodiscard]] static std::string quote(std::string_view value) {
    std::string result = "\"";
    for (char character : value) {
      switch (character) {
      case '\\':
        result += "\\\\";
        break;
      case '"':
        result += "\\\"";
        break;
      case '\n':
        result += "\\n";
        break;
      case '\r':
        result += "\\r";
        break;
      case '\t':
        result += "\\t";
        break;
      case '\0':
        result += "\\000";
        break;
      default:
        result += character;
      }
    }
    result += '"';
    return result;
  }

  std::ostringstream output;
  CppStandard standard;
  TargetInfo target;
  std::unordered_set<const NamespaceAliasDecl *> forwardedAliases;
  std::vector<std::string> sourceNamespaces;
  const TypeRef *currentReturnType = nullptr;
  std::size_t indentation = 0;
};

} // namespace lang
