#pragma once

#include "gti/ast.h"

#include <iomanip>
#include <limits>
#include <sstream>
#include <string>
#include <string_view>
#include <unordered_set>
#include <variant>
#include <vector>

namespace lang {

class CppEmitter final : public ExprVisitor, public StmtVisitor {
public:
  std::string emit(const Program &program) {
    output.str("");
    output.clear();
    indentation = 0;
    forwardedAliases.clear();
    sourceNamespaces.clear();

    output << "// Generated by GTI.\n"
              "#include <string>\n";
    if (containsRuntimeBinding(program.declarations())) {
      output << "#include <gti/runtime.hpp>\n";
    }
    output << '\n';

    emitForwardDeclarations(program);
    for (const StmtPtr &declaration : program.declarations()) {
      declaration->accept(*this);
      output << '\n';
    }
    return output.str();
  }

  void visitBlockStmt(const BlockStmt &stmt) override {
    writeIndent();
    emitBlock(stmt);
  }

  void visitClassDecl(const ClassDecl &stmt) override {
    writeIndent();
    output << "class " << stmt.name().lexeme << " {\n";
    ++indentation;
    writeIndent();
    output << "public:\n";
    ++indentation;
    for (const StmtPtr &member : stmt.members()) {
      member->accept(*this);
    }
    --indentation;
    --indentation;
    writeIndent();
    output << "};\n";
  }

  void visitEmptyStmt(const EmptyStmt &) override {
    writeIndent();
    output << ";\n";
  }

  void visitExpressionStmt(const ExpressionStmt &stmt) override {
    writeIndent();
    emitExpression(stmt.expression());
    output << ";\n";
  }

  void visitForStmt(const ForStmt &stmt) override {
    writeIndent();
    output << "for (";
    emitForInitializer(stmt.initializer());
    output << "; ";
    emitExpression(stmt.condition());
    output << "; ";
    emitExpression(stmt.increment());
    output << ")";
    emitControlledBody(stmt.body());
  }

  void visitFunctionDecl(const FunctionDecl &stmt) override {
    if (stmt.runtimeBinding()) {
      return;
    }
    writeIndent();
    emitFunctionSignature(stmt);
    if (stmt.body()) {
      output << ' ';
      emitBlock(*stmt.body());
    } else {
      output << ";\n";
    }
  }

  void visitIfStmt(const IfStmt &stmt) override {
    writeIndent();
    output << "if (";
    emitExpression(stmt.condition());
    output << ")";
    emitControlledBody(stmt.thenBranch());

    if (stmt.elseBranch()) {
      writeIndent();
      output << "else";
      emitControlledBody(stmt.elseBranch());
    }
  }

  void visitNamespaceAliasDecl(const NamespaceAliasDecl &stmt) override {
    if (forwardedAliases.contains(&stmt)) {
      return;
    }
    writeIndent();
    output << "namespace " << stmt.name().lexeme << " = ";
    emitNamePath(stmt.target());
    output << ";\n";
  }

  void visitNamespaceDecl(const NamespaceDecl &stmt) override {
    writeIndent();
    output << "namespace " << emittedNamespaceName(stmt.name()) << " {\n";
    sourceNamespaces.emplace_back(stmt.name().lexeme);
    ++indentation;
    for (const StmtPtr &declaration : stmt.declarations()) {
      declaration->accept(*this);
      output << '\n';
    }
    --indentation;
    sourceNamespaces.pop_back();
    writeIndent();
    output << "}\n";
  }

  void visitReturnStmt(const ReturnStmt &stmt) override {
    writeIndent();
    output << "return";
    if (stmt.value()) {
      output << ' ';
      emitExpression(stmt.value());
    }
    output << ";\n";
  }

  void visitVariableDecl(const VariableDecl &stmt) override {
    writeIndent();
    emitVariable(stmt);
    output << ";\n";
  }

  void visitWhileStmt(const WhileStmt &stmt) override {
    writeIndent();
    output << "while (";
    emitExpression(stmt.condition());
    output << ")";
    emitControlledBody(stmt.body());
  }

  void visitAssignExpr(const Assign &expr) override {
    output << '(' << expr.name().lexeme << ' ' << expr.oper().lexeme << ' ';
    emitExpression(expr.value());
    output << ')';
  }

  void visitBinaryExpr(const Binary &expr) override {
    output << '(';
    emitExpression(expr.left());
    output << ' ' << operatorSpelling(expr.oper()) << ' ';
    emitExpression(expr.right());
    output << ')';
  }

  void visitCallExpr(const Call &expr) override {
    emitExpression(expr.callee());
    output << '(';
    for (std::size_t index = 0; index < expr.arguments().size(); ++index) {
      if (index > 0) {
        output << ", ";
      }
      emitExpression(expr.arguments().at(index));
    }
    output << ')';
  }

  void visitGetExpr(const Get &expr) override {
    output << '(';
    emitExpression(expr.object());
    output << ")." << expr.name().lexeme;
  }

  void visitGroupingExpr(const Grouping &expr) override {
    output << '(';
    emitExpression(expr.expression());
    output << ')';
  }

  void visitLiteralExpr(const LiteralExpr &expr) override {
    const Literal &literal = expr.value();
    if (std::holds_alternative<std::nullptr_t>(literal)) {
      output << "nullptr";
    } else if (const auto *value = std::get_if<int>(&literal)) {
      output << *value;
    } else if (const auto *value = std::get_if<double>(&literal)) {
      output << std::setprecision(std::numeric_limits<double>::max_digits10)
             << *value;
    } else if (const auto *value = std::get_if<std::string>(&literal)) {
      output << "std::string{" << quote(*value) << '}';
    } else if (const auto *value = std::get_if<bool>(&literal)) {
      output << (*value ? "true" : "false");
    } else {
      output << "{}";
    }
  }

  void visitLogicalExpr(const Logical &expr) override {
    output << '(';
    emitExpression(expr.left());
    output << ' ' << operatorSpelling(expr.oper()) << ' ';
    emitExpression(expr.right());
    output << ')';
  }

  void visitPostfixExpr(const Postfix &expr) override {
    output << '(';
    emitExpression(expr.expression());
    output << expr.oper().lexeme << ')';
  }

  void visitQualifiedNameExpr(const QualifiedName &expr) override {
    emitNamePath(expr.name());
  }

  void visitSelfExpr(const Self &) override { output << "(*this)"; }

  void visitSetExpr(const Set &expr) override {
    output << "((";
    emitExpression(expr.object());
    output << ")." << expr.name().lexeme << ' ' << expr.oper().lexeme << ' ';
    emitExpression(expr.value());
    output << ')';
  }

  void visitUnaryExpr(const Unary &expr) override {
    output << '(' << operatorSpelling(expr.oper());
    emitExpression(expr.right());
    output << ')';
  }

  void visitVariableExpr(const Variable &expr) override {
    output << expr.name().lexeme;
  }

private:
  void emitForwardDeclarations(const Program &program) {
    const bool emittedTypes =
        emitTypeForwardDeclarations(program.declarations());
    const bool emittedAliases = emitAliasDeclarations(program.declarations());
    const bool emittedFunctions =
        emitFunctionForwardDeclarations(program.declarations());
    if (emittedTypes || emittedAliases || emittedFunctions) {
      output << '\n';
    }
  }

  bool emitTypeForwardDeclarations(const StmtList &declarations) {
    bool emitted = false;
    for (const StmtPtr &declaration : declarations) {
      if (const auto *classDecl =
              dynamic_cast<const ClassDecl *>(declaration.get())) {
        writeIndent();
        output << "class " << classDecl->name().lexeme << ";\n";
        emitted = true;
      }
    }
    for (const StmtPtr &declaration : declarations) {
      if (const auto *namespaceDecl =
              dynamic_cast<const NamespaceDecl *>(declaration.get())) {
        writeIndent();
        output << "namespace " << emittedNamespaceName(namespaceDecl->name())
               << " {\n";
        sourceNamespaces.emplace_back(namespaceDecl->name().lexeme);
        ++indentation;
        emitTypeForwardDeclarations(namespaceDecl->declarations());
        --indentation;
        sourceNamespaces.pop_back();
        writeIndent();
        output << "}\n";
        emitted = true;
      }
    }
    return emitted;
  }

  bool emitAliasDeclarations(const StmtList &declarations) {
    bool emitted = false;
    for (const StmtPtr &declaration : declarations) {
      if (const auto *alias =
              dynamic_cast<const NamespaceAliasDecl *>(declaration.get())) {
        writeIndent();
        output << "namespace " << alias->name().lexeme << " = ";
        emitNamePath(alias->target());
        output << ";\n";
        forwardedAliases.insert(alias);
        emitted = true;
      } else if (const auto *namespaceDecl =
                     dynamic_cast<const NamespaceDecl *>(declaration.get());
                 namespaceDecl != nullptr &&
                 containsNamespaceAlias(namespaceDecl->declarations())) {
        writeIndent();
        output << "namespace " << emittedNamespaceName(namespaceDecl->name())
               << " {\n";
        sourceNamespaces.emplace_back(namespaceDecl->name().lexeme);
        ++indentation;
        emitAliasDeclarations(namespaceDecl->declarations());
        --indentation;
        sourceNamespaces.pop_back();
        writeIndent();
        output << "}\n";
        emitted = true;
      }
    }
    return emitted;
  }

  bool emitFunctionForwardDeclarations(const StmtList &declarations) {
    bool emitted = false;
    for (const StmtPtr &declaration : declarations) {
      if (const auto *function =
              dynamic_cast<const FunctionDecl *>(declaration.get());
          function != nullptr && !function->runtimeBinding()) {
        writeIndent();
        emitFunctionSignature(*function);
        output << ";\n";
        emitted = true;
      }
    }
    for (const StmtPtr &declaration : declarations) {
      if (const auto *namespaceDecl =
              dynamic_cast<const NamespaceDecl *>(declaration.get());
          namespaceDecl != nullptr &&
          containsFunction(namespaceDecl->declarations())) {
        writeIndent();
        output << "namespace " << emittedNamespaceName(namespaceDecl->name())
               << " {\n";
        sourceNamespaces.emplace_back(namespaceDecl->name().lexeme);
        ++indentation;
        emitFunctionForwardDeclarations(namespaceDecl->declarations());
        --indentation;
        sourceNamespaces.pop_back();
        writeIndent();
        output << "}\n";
        emitted = true;
      }
    }
    return emitted;
  }

  [[nodiscard]] static bool containsNamespaceAlias(
      const StmtList &declarations) {
    for (const StmtPtr &declaration : declarations) {
      if (dynamic_cast<const NamespaceAliasDecl *>(declaration.get()) !=
          nullptr) {
        return true;
      }
      if (const auto *namespaceDecl =
              dynamic_cast<const NamespaceDecl *>(declaration.get());
          namespaceDecl != nullptr &&
          containsNamespaceAlias(namespaceDecl->declarations())) {
        return true;
      }
    }
    return false;
  }

  [[nodiscard]] static bool containsFunction(const StmtList &declarations) {
    for (const StmtPtr &declaration : declarations) {
      if (const auto *function =
              dynamic_cast<const FunctionDecl *>(declaration.get());
          function != nullptr && !function->runtimeBinding()) {
        return true;
      }
      if (const auto *namespaceDecl =
              dynamic_cast<const NamespaceDecl *>(declaration.get());
          namespaceDecl != nullptr &&
          containsFunction(namespaceDecl->declarations())) {
        return true;
      }
    }
    return false;
  }

  [[nodiscard]] static bool
  containsRuntimeBinding(const StmtList &declarations) {
    for (const StmtPtr &declaration : declarations) {
      if (const auto *function =
              dynamic_cast<const FunctionDecl *>(declaration.get());
          function != nullptr && function->runtimeBinding()) {
        return true;
      }
      if (const auto *namespaceDecl =
              dynamic_cast<const NamespaceDecl *>(declaration.get());
          namespaceDecl != nullptr &&
          containsRuntimeBinding(namespaceDecl->declarations())) {
        return true;
      }
    }
    return false;
  }

  void emitFunctionSignature(const FunctionDecl &function) {
    emitType(function.returnType());
    output << ' ' << function.name().lexeme << '(';
    for (std::size_t index = 0; index < function.parameters().size(); ++index) {
      if (index > 0) {
        output << ", ";
      }
      const Parameter &parameter = function.parameters().at(index);
      if (parameter.mutability == Mutability::Immutable) {
        output << "const ";
      }
      emitType(parameter.type);
      if (parameter.mutability == Mutability::Immutable &&
          parameter.type.name.last().kind == TokenKind::STRING_TYPE) {
        output << " &";
      }
      if (!parameter.name.lexeme.empty()) {
        output << ' ' << parameter.name.lexeme;
      }
    }
    output << ')';
  }

  void emitType(const TypeRef &type) {
    if (type.name.last().kind == TokenKind::STRING_TYPE) {
      output << "std::string";
      return;
    }
    emitNamePath(type.name);
  }

  void emitNamePath(const NamePath &path) {
    for (std::size_t index = 0; index < path.segments.size(); ++index) {
      if (index > 0) {
        output << "::";
      }
      if (index == 0 && path.segments[index].lexeme == "std") {
        output << "gti_std";
      } else {
        output << path.segments[index].lexeme;
      }
    }
  }

  [[nodiscard]] std::string emittedNamespaceName(const Token &name) const {
    return sourceNamespaces.empty() && name.lexeme == "std" ? "gti_std"
                                                              : name.lexeme;
  }

  void emitVariable(const VariableDecl &variable) {
    if (!variable.isMutable()) {
      output << "const ";
    }
    emitType(variable.type());
    output << ' ' << variable.name().lexeme;
    if (variable.initializer()) {
      output << " = ";
      emitExpression(variable.initializer());
    }
  }

  void emitForInitializer(const StmtPtr &initializer) {
    if (const auto *variable =
            dynamic_cast<const VariableDecl *>(initializer.get())) {
      emitVariable(*variable);
    } else if (const auto *expression =
                   dynamic_cast<const ExpressionStmt *>(initializer.get())) {
      emitExpression(expression->expression());
    }
  }

  void emitControlledBody(const StmtPtr &body) {
    if (const auto *block = dynamic_cast<const BlockStmt *>(body.get())) {
      output << ' ';
      emitBlock(*block);
      return;
    }

    output << '\n';
    ++indentation;
    body->accept(*this);
    --indentation;
  }

  void emitBlock(const BlockStmt &block) {
    output << "{\n";
    ++indentation;
    for (const StmtPtr &statement : block.statements()) {
      statement->accept(*this);
    }
    --indentation;
    writeIndent();
    output << "}\n";
  }

  void emitExpression(const ExprPtr &expression) {
    if (expression) {
      expression->accept(*this);
    }
  }

  void writeIndent() {
    for (std::size_t index = 0; index < indentation; ++index) {
      output << "  ";
    }
  }

  [[nodiscard]] static std::string_view operatorSpelling(const Token &oper) {
    if (oper.kind == TokenKind::AND) {
      return "&&";
    }
    if (oper.kind == TokenKind::OR) {
      return "||";
    }
    return oper.lexeme;
  }

  [[nodiscard]] static std::string quote(std::string_view value) {
    std::string result = "\"";
    for (char character : value) {
      switch (character) {
      case '\\':
        result += "\\\\";
        break;
      case '"':
        result += "\\\"";
        break;
      case '\n':
        result += "\\n";
        break;
      case '\r':
        result += "\\r";
        break;
      case '\t':
        result += "\\t";
        break;
      default:
        result += character;
      }
    }
    result += '"';
    return result;
  }

  std::ostringstream output;
  std::unordered_set<const NamespaceAliasDecl *> forwardedAliases;
  std::vector<std::string> sourceNamespaces;
  std::size_t indentation = 0;
};

} // namespace lang
